version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: cargarage
      MYSQL_USER: root
      MYSQL_PASSWORD: Wiss2024
      MYSQL_ROOT_PASSWORD: Wiss2024
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cargarage
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Wiss2024
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  db-data:
